meta:
  version: latest
  name: my-mqtt-connector
  type: mqtt-source
  topic: mqtt-topic
  create-topic: true
mqtt:  
  url: "mqtt://test.mosquitto.org/"  
  topic: "ag-mqtt-topic-demo"
  client_id: "my_mqtt"
  timeout:
    secs: 30
    nanos: 0
  payload_output_type: json

