meta:
  version: latest
  name: test-env-secret-binary-output-type
  type: mqtt-source
  topic: test-env-secret-binary-output-type
  create-topic: true
mqtt:  
  url:
    secret:
      name: MQTT_URL
  topic: test-env-secret-binary-output-type
  client_id: "test-env-secret-binary-output-type"
  timeout:
    secs: 30
    nanos: 0
  payload_output_type: binary
